---
- import_playbook: determine-switch-model.yml

- hosts: Aruba_OSS
  gather_facts: False
  collections:
    - arubanetworks.aos_switch
  vars:
    ansible_connection: network_cli
  tasks:
    - name: Reboot via {{ boot_image }} image
      arubaoss_command:
        commands:
        - command: 'boot system flash {{ boot_image }}'
          prompt:
            - '.*Continue.*'
          answer:
            - y

- hosts: AOSCX
  gather_facts: False
  vars:
    ansible_connection: httpapi
  collections:
    - arubanetworks.aoscx
  tasks:
    - name: Boot to {{ boot_image }}
      aoscx_boot_firmware:
        partition_name: '{{ boot_image }}'
