---
- hosts: localhost
  gather_facts: False
  tasks:
  
  - name: Download pandas package
      ansible.builtin.shell: pip install pandas -y
      become: true
      
  - name: Execute .xlsx output script
    script: parsing-switch-info.py
    delegate_to: localhost
