---
- hosts: localhost
  gather_facts: False
  tasks:
  
  - name: Download pandas package
    bash: pip install pandas -y
  
  
  - name: Execute .xlsx output script
    script: parsing-switch-info.py
    delegate_to: localhost
