---
- hosts: localhost
  gather_facts: False
  tasks:
  
  - name: Download pandas package
    ansible.builtin.pip:
      name: pandas
      state: present
      
  - name: Execute .xlsx output script
    script: parsing-switch-info.py
    delegate_to: localhost
