---
- hosts: "{{ host_var }}"
  gather_facts: False
  vars_files:
    - ./vars/vault.yml
    - ./vars/var.yml
  collections:
    - arubanetworks.aos_switch
  vars:
    ansible_connection: network_cli
  tasks:
  - name: "Store information about switches"
    arubaoss_command:
      commands: ['show system', 'show modules']
      output_file: "{{ inventory_hostname }}.txt"


- hosts: localhost
  gather_facts: False
  tasks:
  - name: Download pandas package
    ansible.builtin.pip:
      name: pandas
      state: present
 
  - name: Download openpyxl package
    ansible.builtin.pip:
      name: openpyxl
      state: present

  - name: Download paramiko package
    ansible.builtin.pip:
      name: paramiko
      state: present
      
  - name: Execute .xlsx output script
    script: python/parsing-switch-info.py
    delegate_to: localhost
