---
- import_playbook: determine-switch-model.yml

- hosts: AOSCX
  gather_facts: False
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: httpapi
  tasks:
  - name: Create VLAN
    aoscx_vlan:
      vlan_id: "{{ survey_vlan_id }}"
      name: "{{ survey_vlan_name }}"
      description: "{{ survey_vlan_desc }}"
      state: create


- hosts: Aruba_OSS
  gather_facts: False
  collections:
    - arubanetworks.aos_switch
  vars:
    ansible_connection: network_cli
  tasks:
  - name: Create VLAN
    arubaoss_command:
      commands: ['configure', 'vlan {{ survey_vlan_id }}', 'name {{ survey_vlan_name }}', 'wr mem']
