---
- hosts: "{{ host_var }}"
  vars_files:
    - ./vars/vault.yml
    - ./vars/var.yml
  collections:
    - arubanetworks.aos_switch
  vars:
    ansible_connection: network_cli
    ansible_network_os: arubanetworks.aos_switch.arubaoss

  tasks:
    - name: Show running-config, show version commands output to a file
      arubaoss_command:
        commands: ['show run', 'show version']
        output_file: "{{ inventory_hostname }}.cfg"


- hosts: localhost
  gather_facts: False
  tasks:
    - name: Download paramiko package
      ansible.builtin.pip:
        name: paramiko
        state: present
      
    - name: Export cfg files trough sftp
      script: python/export-cfg-sftp-{{ freq_var }}.py
      delegate_to: localhost

 
