---
- name: Ping all hosts
  hosts: "{{ host_var }}"
  vars_files:
    - ./vars/vault.yml
    - ./vars/var.yml
  gather_facts: false
  tasks:
    - name: Ping host
      ping:
      register: output
    - debug:
        var: output
