---
- hosts: all
  collections:
    - arubanetworks.aos_switch
  vars:
    ansible_connection: network_cli
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: False
  tasks:
    - name: Execute show version on the switch
      arubaoss_command:
        commands: show version
      register: command_output
    - debug:
        var: command_output.stdout_lines
