---
- import_playbook: determine-switch-model.yml

- hosts: Aruba_OSS
  gather_facts: False
  collections:
    - arubanetworks.aos_switch
  vars:
    ansible_connection: network_cli
  tasks:
    - name: Upload via TFTP
      arubaoss_command:
        commands:
        - command: 'copy tftp flash 10.50.33.21 {{ group_2540_image }} primary'
          prompt:
            - '.*Continue.*'
          answer:
            - y
    - name: Show Flash to confirm upload
      arubaoss_command:
        commands:
        - command: 'show flash'



- hosts: AOSCX
  gather_facts: False
  vars:
    ansible_connection: httpapi
  collections:
    - arubanetworks.aoscx
  tasks:
    - name: Upload firmware to primary through HTTP
      aoscx_upload_firmware:
        partition_name: 'primary'
        remote_firmware_file_path: 'http://10.50.33.21:8000/{{ group_6100_image }}'
        vrf: 'default'
